### ISSUE TITLE
Pixel art not showing up as intended

### ISSUE THREAD

**Issue by mikhaelcool7** [Nolonar/RM_Plugins-Pixelate#1]
With the plugin:
![image](https://user-images.githubusercontent.com/5103276/157907673-6a709b70-5365-4bda-8ee8-79db5ca61968.png)
Without:
![image](https://user-images.githubusercontent.com/5103276/157907785-d5c5552c-3b81-4a5e-aeba-f916a3fe9717.png)
The games window size and the image match the exact same resolution of 1280x800 making it a 1:1 but it certainly doesn't look that way

Preview of the image without any filtering in Aseprite:
![image](https://user-images.githubusercontent.com/5103276/157908605-52c304bb-df05-4093-85b4-56818224e19e.png)
Please open and view the images as Github may make the tiny image thumbnails look different.

**Comment by Nolonar** [comment]
It looks like your image is being downscaled (notice the black borders left and right).

Does your screen have a resolution of 1280x800 pixels? If so, it's possible the window borders are "stealing" some of the 800 vertical pixels, leaving less than 800 pixels for the image, and in turn forcing it to downscale to maintain its aspect ratio.

If that's the case, I could attempt to add an option that disables the plugin if `innerWidth` or `innerHeight` is less than the game's intended resolution. Would that be an acceptable solution?

**Comment by mikhaelcool7** [comment]
> It looks like your image is being downscaled (notice the black borders left and right).
> 
> Does your screen have a resolution of 1280x800 pixels? If so, it's possible the window borders are "stealing" some of the 800 vertical pixels, leaving less than 800 pixels for the image, and in turn forcing it to downscale to maintain its aspect ratio.
> 
> If that's the case, I could attempt to add an option that disables the plugin if `innerWidth` or `innerHeight` is less than the game's intended resolution. Would that be an acceptable solution?

My screens resolution is 1920x1080
![image](https://user-images.githubusercontent.com/5103276/158075562-a3ec8f15-fee5-4203-aeec-d6649ade6bfd.png)
These are the resolution settings in RPG Maker MZ v1.4.4 (Steam)
![image](https://user-images.githubusercontent.com/5103276/158075584-55f3ee30-aad2-4ff3-85ba-eac1c13a5a19.png)
Images from a debugger and it does show some resolution differences
![image](https://user-images.githubusercontent.com/5103276/158075884-dd64904f-518c-46b2-bae0-b410f4879caf.png)
![image](https://user-images.githubusercontent.com/5103276/158076121-0208fbc4-edb6-4410-91ea-9a70983f562d.png)

**Comment by mikhaelcool7** [comment]
![image](https://user-images.githubusercontent.com/5103276/158076380-dfefe891-6438-41fc-83d3-dc31bdcfcf28.png)
The scale of 125% was the issue all along
![image](https://user-images.githubusercontent.com/5103276/158076492-98cf5dd0-661d-4f37-8ba3-a64662a99939.png)

**Comment by Nolonar** [comment]
I've done a bit of research. At 125% scaling, the Windows 11 taskbar is 60 pixels high, and the RPG Maker MZ window's title bar is roughly 38 pixels high. Put together, that's 98 pixels you're losing. Also, your game will be upscaled from 1280x800 pixels to 1600x1000 pixels. 1920 is enough to fit 1600, but 1080 is not enough to fit 1098. That's why your game gets downscaled.

Setting the scaling to 100% does solve the problem with your window getting downscaled, but your players might not want to do this.

I've now released [version 1.1.0][1] with the new "hybrid pixelate" option. When turned ON, this option will disable pixelate when the window is smaller than the game's resolution. This should fix the problem you're facing with 125% scaling, while still giving you pixel-perfect graphics at 100% scaling.


  [1]: https://github.com/Nolonar/RM_Plugins-Pixelate/releases/latest/download/N_Pixelate.js
